import { render } from '@testing-library/react'
import React, { useContext } from 'react'
import '../bootstrap/bootstrap.css'
import image from '../images/teacher-profile-01.png'
import './grades.css'